//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int Id { get; set; }
        public int ContractNumber { get; set; }
        public int Customer { get; set; }
        public int Price { get; set; }
        public double Commission { get; set; }
        public System.DateTime Date { get; set; }
        public int Realtor { get; set; }
        public int RealEstateObject { get; set; }
        public int Owner { get; set; }
        public int TypeContract { get; set; }
        public int TypeDeal { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual RealEstateObjects RealEstateObjects { get; set; }
        public virtual TypeContracts TypeContracts { get; set; }
        public virtual TypeDeals TypeDeals { get; set; }
    }
}
