//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateAgencyDbEntities : DbContext
    {
        public RealEstateAgencyDbEntities()
            : base("name=RealEstateAgencyDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<AttributesName> AttributesName { get; set; }
        public virtual DbSet<AttributesOrders> AttributesOrders { get; set; }
        public virtual DbSet<AttributesRealEstateObjects> AttributesRealEstateObjects { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<RealEstateObjects> RealEstateObjects { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusOrders> StatusOrders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeContracts> TypeContracts { get; set; }
        public virtual DbSet<TypeDeals> TypeDeals { get; set; }
        public virtual DbSet<TypeOrders> TypeOrders { get; set; }
        public virtual DbSet<TypeRealEstateObjects> TypeRealEstateObjects { get; set; }
    }
}
