//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.AttributesOrders = new HashSet<AttributesOrders>();
        }
    
        public int Id { get; set; }
        public int StatusOrder { get; set; }
        public int Client { get; set; }
        public int Agent { get; set; }
        public int TypeRealEstate { get; set; }
        public int IdAddress { get; set; }
        public int MinPrice { get; set; }
        public int MaxPrice { get; set; }
        public int TypeOrder { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Agents Agents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributesOrders> AttributesOrders { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual StatusOrders StatusOrders { get; set; }
        public virtual TypeOrders TypeOrders { get; set; }
        public virtual TypeRealEstateObjects TypeRealEstateObjects { get; set; }
    }
}
